### ISSUE TITLE
Broken Blog links

### ISSUE THREAD

**Issue by grizznaut** [payjoin/payjoindevkit.org#6]
The "Blog" link in the header and footer of the website both direct to https://payjoindevkit.org/blog/ which is just a blank page. Should they link to https://payjoin.substack.com/ perhaps?

**Comment by DanGould** [comment]
Thanks for the report. Strange, it's working on my local environment but not working on payjoindevkit.org. There should be a blog section with devkit specific posts. I'll have a chance to look at it within a week.

**Comment by DanGould** [comment]
fixed by spacebear in #10
